FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src ./src
COPY scripts/generate_transactions.py ./scripts/generate_transactions.py
ENV PYTHONPATH=/app/src
CMD ["python", "scripts/generate_transactions.py"]
