FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY src ./src
COPY scripts/train.py ./scripts/train.py
ENV PYTHONPATH=/app/src
ENV MODEL_LOCAL_PATH=/app/artifacts/model.joblib
RUN mkdir -p /app/artifacts
CMD ["python", "scripts/train.py"]
